Repository hzuapps/uml-modeling-2020, pull requests merged in 2020-03, with the labels that each got.

#504 #2 提交实验二代码
  students/1714080902606/UseCaseDiagram1.jpg
  students/1714080902606/lab1.md
  students/1714080902606/lab2.md
  students/1714080902606/mypicture.jpg.png
Labels: Example, Good

#524 #2 提交实验二代码
  students/1714080902624/Lab2_UseCaseDiagram1.jpg
  students/1714080902624/lab1.md
  students/1714080902624/lab2.md
Labels: Example, Good

#529 #2实验二：用例建模
  students/1714080902212/UseCaseDiagram1.jpg
  students/1714080902212/lab2.md
Labels: Good

#575 #2 #390 提交实验二代码
  students/1714080902401/UseCaseDiagram1.jpg
  students/1714080902401/lab1.jpg
  students/1714080902401/lab1.md
  students/1714080902401/lab2.md
Labels: Good

#574 #2 #364 实验二实验报告
  students/1714080901143/Lab2_UseCaseDiagram.jpg
  students/1714080901143/lab2.md
Labels: Good

#631 #2 #596 实验二用例图画图
  students/1714080902424/Lab2_UseCaseDiagram.jpg
  students/1714080902424/lab2.md
Labels: Good

#625 #2 #282 提交实验二代码
  students/1714080902407/lab1.md
  students/1714080902407/lab2.md
  students/1714080902407/lab2_UseCaseDiagram.jpg
Labels: Good

#701 #2 #428 实验二用例图及之前报告提交
  students/1709081602513/UseCaseDiagram_lab2.jpg
  students/1709081602513/lab1.md
  students/1709081602513/lab2.md
Labels: Good

#696 #2 #270 修改实验二文档
  students/1714080902130/Lab2_UseCaseDiagram1.jpg
  students/1714080902130/lab2.md
Labels: Good

#727 #2 #111 实验二：用例建模
  students/1714080902339/Lab2_UseCaseDiagram.jpg
  students/1714080902339/lab1.md
  students/1714080902339/lab2.md
Labels: Good

#792 #2 #458 实验二：用例建模
  students/1714080902624/lab1.md
  students/1714080902624/lab2.md
Labels: Good

#788 #2 #604 实验二：用例建模
  students/1714080902116/Lab2_UseCaseDiagram.jpg
  students/1714080902116/lab1.md
  students/1714080902116/lab2.md
Labels: Good

#830 #2 #152 实验二：用例建模
  students/1714080902627/lab1.md
  students/1714080902627/lab2.md
  students/1714080902627/mymodel.jpg
  students/1714080902627/mymodel1.jpg
Labels: Good

#877 #2 #464 提交实验二
  students/1714080902437/Lab2_UseCaseDiagram.jpg
  students/1714080902437/Lab2_UseCaseDiagram3.jpg
  students/1714080902437/lab2.md
Labels: Good

#909 #2 #140 实验二：用例建模
  students/1707080714328/Lab2_UseCaseDiagram.jpg
  students/1707080714328/lab1.md
  students/1707080714328/lab2.md
Labels: Good

#843 #2 #624 提交实验二
  students/1714080902127/Lab2_UseCaseDiagram.jpg
  students/1714080902127/lab2.md
Labels: Good

#844 #2 #184 实验二：用例建模
  students/1714080902436/lab1.md
  students/1714080902436/lab2.md
  students/1714080902436/model2.jpg
Labels: Good

#852 #2 #403 实验二：用例建模
  students/1714080902201/lab1.md
  students/1714080902201/lab2.md
  students/1714080902201/lab2_UseCaseDiagram.jpg
  students/1714080902201/soft.jpg
Labels: Good

#860 #2 #311 提交实验二文档
  students/1714080902534/Lab2_UseCaseDiagram.jpg
  students/1714080902534/lab1.md
  students/1714080902534/lab2.md
Labels: Good

#869 #2 #466 实验二：用例建模
  students/1714080902604/lab1.md
  students/1714080902604/lab2.md
Labels: Good

#879 #2 #866 实验二：用例建模
  students/soft1714080902111/lab2.md
  students/soft1714080902111/model2.jpg
Labels: Good

#881 #2 #270 实验二
  students/1714080902130/lab2.md
Labels: Good

#898 #2 #614 实验二：用例建模
  students/1714080902620/Lab2.md
  students/1714080902620/Lab2_UseCaseDiagram1.jpg
Labels: Good

#919 #2 #474 实验二
  students/1714080902528/Lab2_UseCaseDiagram1.jpg
  students/1714080902528/lab1.md
  students/1714080902528/lab2.md
Labels: Good

#920 #2 #564 实验二：用例建模
  students/1714080902531/UseCaseDiagram1.jpg
  students/1714080902531/lab1.md
  students/1714080902531/lab2.md
Labels: Good

#923 #2 #213 实验二：用例建模
  students/1714080902207/Lab02_UseCaseDiagram1.jpg
  students/1714080902207/lab02.md
Labels: Good

#927 #2 #581 实验二：用例建模
  students/1714080902409/Lab2-UseCaseDiagram.jpg
  students/1714080902409/Lab2.md
Labels: Good

#933 #2 #703 实验二：用例建模
  students/1714080902133/image/1.png
  students/1714080902133/image/ClassDiagram1.jpg
  students/1714080902133/image/UseCaseDiagram1.png
  students/1714080902133/lab1.md
  students/1714080902133/lab2.md
Labels: Good

#939 #2 #224 实验二：用例建模
  students/1714080902131/Lab2_UseCaseDiagram.jpg
  students/1714080902131/lab1.md
  students/1714080902131/lab2.md
Labels: Good

#940 #2 #210 实验二：用例建模
  students/1714080902124/Lab2_UseCaseDiagram.png
  students/1714080902124/实验二.md
Labels: Good

#942 #2 #282 修改实验二用例规约
  students/1714080902407/lab2.md
  students/1714080902407/lab2_UseCaseDiagram.jpg
Labels: Good

#993 #2 #656 实验二：用例建模
  students/1714080902408/sy1/Lab1_UseCaseDiagram.jpg
  students/1714080902408/sy1/lab1.md
  students/1714080902408/sy2/Lab2_UseCaseDiagram.jpg
  students/1714080902408/sy2/lab2.md
Labels: Good

#1192 #2 #1185 Create lab2 && Update lab1
  students/1714080901141/lab1.md
  students/1714080901141/lab2.md
  students/1714080901141/model2.jpg
Labels: Excellent, Good

#1260 #3 #475 提交用例活动图及实验三报告
  students/1714080902533/Lab3_搜索新闻.jpg
  students/1714080902533/Lab3_查看新闻.jpg
  students/1714080902533/Lab3_评论新闻.jpg
  students/1714080902533/lab2.md
  students/1714080902533/lab3.md
Labels: Excellent, Good

#1267 #3 #244 实验3过程建模
  students/1707080412124/Lab3_ActivityDiagram_Check.jpg
  students/1707080412124/Lab3_ActivityDiagram_Register.jpg
  students/1707080412124/lab2.md
  students/1707080412124/lab3.md
Labels: Good

#1334 #3 #489 修改实验三
  students/1714080902617/Lab3_处理订单活动图.jpg
  students/1714080902617/Lab3_提交订单活动图.jpg
  students/1714080902617/Lab3_选桌活动图.jpg
  students/1714080902617/lab3.md
Labels: Good

#1337 #3 #430 实验三：过程建模
  students/1714080902635/lab2.md
  students/1714080902635/lab3.md
  students/1714080902635/修改会员信息.jpg
  students/1714080902635/录入会员信息.jpg
  students/1714080902635/转移积分.jpg
Labels: Excellent

#1344 #3 #437 实验三：过程建模
  students/1714080902431/ActivityDiagram1.jpg
  students/1714080902431/ActivityDiagram2.jpg
  students/1714080902431/ActivityDiagram3.jpg
  students/1714080902431/lab2.md
  students/1714080902431/lab3.md
Labels: Good

#1385 #3 #554 实验三：过程建模
  students/1714080902329/lab3.md
  students/1714080902329/删除人员.jpg
  students/1714080902329/添加人员.jpg
Labels: Excellent

#1393 #3 #495 实验三：过程建模
  students/1714080902639/lab3.md
  students/1714080902639/lab3_ActivityDiagram2.jpg
  students/1714080902639/lab3_ActivityDiagram3.jpg
  students/1714080902639/lab3_ActivityDiagram4.jpg
Labels: Good

#1402 #3 #581 实验三：过程建模
  students/1714080902409/Lab3.md
  students/1714080902409/发布出租信息的活动图.jpg
  students/1714080902409/收藏房源.jpg
Labels: Good

#1419 #3 #352 实验三：过程建模（第一次提交）
  students/1714080902215/0301检测感染活动图.jpg
  students/1714080902215/0302标记车厢活动图.jpg
  students/1714080902215/0303解除标记活动图.jpg
  students/1714080902215/lab3.md
Labels: Good

#1432 #3 #582 实验三：过程建模
  students/1714080902232/lab2.md
  students/1714080902232/lab3.md
  students/1714080902232/寄快递活动图.jpg
  students/1714080902232/查快递活动图.jpg
Labels: Good

#1423 #3 #506 实验三 过程建模(1)
  students/1714080902502/lab2.md
  students/1714080902502/lab3.md
  students/1714080902502/删除新闻的活动图.jpg
  students/1714080902502/添加新闻的活动图.jpg
Labels: Good

#1464 #3 #559 实验三：过程建模
  students/1714080902316/Lab3_ActivityDiagram1.jpg
  students/1714080902316/Lab3_ActivityDiagram2.jpg
  students/1714080902316/lab3.md
Labels: Good

#1452 #2 #652 实验三提交
  students/1713090502212/lad3.md
  students/1713090502212/model3_1.jpg
  students/1713090502212/model3_2.jpg
  students/1713090502212/model3_3.jpg
Labels: Good

#1458 #3 #647 实验三：过程建模
  students/1714080902330/lab3.md
  students/1714080902330/lab3_1.jpg
  students/1714080902330/lab3_2.jpg
  students/1714080902330/lab3_3.jpg
Labels: Good

#1501 # 3 # 417 实验三过程建模
  students/1714080901203/lab2.md
  students/1714080901203/lab3.md
  students/1714080901203/删除食品.jpg
  students/1714080901203/录入食品信息.jpg
Labels: Good

#1498 #3 #299 实验三：过程建模
  students/1714080902205/lab3.md
  students/1714080902205/lab3_ActivityDiagram1.jpg
  students/1714080902205/lab3_ActivityDiagram2.jpg
Labels: Good

#1494 #3 #572 实验三：过程建模
  students/1714080902428/lab2.md
  students/1714080902428/lab3-1.jpg
  students/1714080902428/lab3-2.jpg
  students/1714080902428/lab3-3.jpg
  students/1714080902428/lab3.md
Labels: Good

#1534 #3 Update lab3
  students/1714080902324/lab2.md
  students/1714080902324/lab3.md
  students/1714080902324/lab3_1.jpg
  students/1714080902324/lab3_2.jpg
  students/1714080902324/lab3_3.jpg
Labels: Good

#1626 #3 #226 实验三：过程建模
  students/1714080902234/Issue_Information_ActivityDiagram.jpg
  students/1714080902234/Sign_Up_ActivityDiagram.jpg
  students/1714080902234/lab3.md
Labels: Good

#1631 #3 #703 实验三：过程建模
  students/1714080902133/image/ActivityDiagram1.png
  students/1714080902133/image/ActivityDiagram2.png
  students/1714080902133/image/ActivityDiagram3.png
  students/1714080902133/lab2.md
  students/1714080902133/lab3.md
Labels: Excellent

#1644 #3 #707 实验三：过程建模
  students/1714080902209/HMS301.png
  students/1714080902209/HMS302.png
  students/1714080902209/HMS303.png
  students/1714080902209/lab2.md
  students/1714080902209/lab3.md
Labels: Good

#1673 #4 #5 #244 实验4 5：类建模
  students/1707080412124/Lab4_ClassDiagram_Check.jpg
  students/1707080412124/Lab4_ClassDiagram_Register.jpg
  students/1707080412124/lab4~5.md
Labels: Good

#1674 #4 #5 #430 实验四和五：类建模和高级建模
  students/1714080902635/lab4.md
  students/1714080902635/修改会员信息类.jpg
  students/1714080902635/录入会员信息类.jpg
  students/1714080902635/转移积分类.jpg
Labels: Good

#1676 #4 #5 #1185 Create lab4&5.md
  students/1714080901141/lab2.md
  students/1714080901141/lab3_ActivityDiagram1.jpg
  students/1714080901141/lab3_ActivityDiagram2.jpg
  students/1714080901141/lab4&5.md
  students/1714080901141/lab4&5_ClassDiagram1.png
  students/1714080901141/lab4&5_ClassDiagram2.png
Labels: Excellent

#1678 #4 #5 #530 实验四、五 类建模
  students/1707080714233/lab4.md
  students/1707080714233/lab4_classDiagram1.jpg
  students/1707080714233/lab4_classDiagram2.jpg
Labels: Good

#1669 #4 #5 #466 实验四五：类建模
  students/1714080902604/ActivityDiagram1.jpg
  students/1714080902604/ActivityDiagram2.jpg
  students/1714080902604/ActivityDiagram3.jpg
  students/1714080902604/MVC01.jpg
  students/1714080902604/MVC02.jpg
  students/1714080902604/MVC03.jpg
  students/1714080902604/lab4.md
Labels: Good

#1670 #4 #5 #429 实验四和五：类建模和高级类建模
  students/1714080902638/UseCase.jpg
  students/1714080902638/insertclass.jpg
  students/1714080902638/lab2.md
  students/1714080902638/lab3.md
  students/1714080902638/lab4.md
  students/1714080902638/selectclass.jpg
  students/1714080902638/updataclass.jpg
Labels: Excellent

#1680 #4 #5 #493实验四五：类建模
  students/1714080902611/lab4.md
  students/1714080902611/lab45_photo01.jpg
  students/1714080902611/lab45_photo02.jpg
Labels: Good

#1667 #4 #5 #475 实验四五：类建模
  students/1714080902533/Lab4_搜索新闻.jpg
  students/1714080902533/Lab4_查看新闻.jpg
  students/1714080902533/Lab4_评论新闻.jpg
  students/1714080902533/lab4.md
Labels: Good

#1663 #4 #5 #458 实验四五：类建模
  students/1714080902624/ClassDiagram1.jpg
  students/1714080902624/ClassDiagram2.jpg
  students/1714080902624/lab4.md
Labels: Good

#1665 #4 #5 #152实验四五：类建模
  students/1714080902627/Class1.jpg
  students/1714080902627/Class2.jpg
  students/1714080902627/lab4.md
Labels: Good

#1685 #4 #5 #434 实验四、五：类建模
  students/1714080901108/lab45.md
  students/1714080901108/lab45_deliver.jpg
  students/1714080901108/lab45_order.jpg
  students/1714080901108/lab45_upload.jpg
Labels: Good

#1668 #4 #5 #505 实验四五：类建模
  students/1714080902532/lab4.md
  students/1714080902532/shiyan4-1.jpg
  students/1714080902532/shiyan4-2.jpg
Labels: Good

#1684 #4 #5 #91 实验四五：类建模和高级类建模
  students/1714080902306/lab2.md
  students/1714080902306/lab4.md
  students/1714080902306/修改座位信息类图.jpg
  students/1714080902306/录入座位信息类图.jpg
  students/1714080902306/预约座位.jpg
  students/1714080902306/预约座位类图.jpg
Labels: Good

#1691 #4 #5 #596 实验四类建模和实验五高级类建模
  students/1714080902424/lab4-5.md
  students/1714080902424/录入宠物病征的类图.jpg
  students/1714080902424/录入诊断信息的类图.jpg
  students/1714080902424/查看诊断信息的类图.jpg
Labels: Good

#1699 #4 #5 #685 实验四和五：类建模和高级类建模
  students/1714080902208/lab-04-05.md
  students/1714080902208/model0405-01.png
  students/1714080902208/model0405-02.png
  students/1714080902208/model0405-03.png
Labels: Good

#1700 #4 #5 #443 实验四五：类建模
  students/1714080902417/Lab45.md
  students/1714080902417/Lab45_ClassDiagram1.jpg
  students/1714080902417/Lab45_ClassDiagram2.jpg
Labels: Good

#1701 #4 #5 #656 实验四&五：类建模&高级建模
  students/1714080902408/sy4&5/Lab4_ClassDiagram1.jpg
  students/1714080902408/sy4&5/Lab4_ClassDiagram2.jpg
  students/1714080902408/sy4&5/lab4&5.md
Labels: Good

#1688 #4 #5 #562 修改实验三 & 提交实验四、五：类建模
  students/1714080902322/ActivityDiagram1.png
  students/1714080902322/ActivityDiagram2.png
  students/1714080902322/ActivityDiagram3.png
  students/1714080902322/ClassDiagram1.png
  students/1714080902322/ClassDiagram2.png
  students/1714080902322/ClassDiagram3.png
  students/1714080902322/lab4.md
Labels: Good

#1689 #4 #5 #111 实验四、五 类建模
  students/1714080902339/Lab4_ClassDiagram1.jpg
  students/1714080902339/Lab4_ClassDiagram2.jpg
  students/1714080902339/Lab4_ClassDiagram3.jpg
  students/1714080902339/lab4.md
Labels: Good

#1707 #4 #537 实验四和实验五 类建模
  students/1714080902637/lab3.md
  students/1714080902637/lab4.md
  students/1714080902637/lab4_1.jpg
  students/1714080902637/lab4_2.jpg
  students/1714080902637/lab4_3.jpg
Labels: Good

#1711 #4 #5 #489 实验四五：类建模
  students/1714080902617/lab2.md
  students/1714080902617/lab4-5.md
  students/1714080902617/lab_4处理订单MVC.jpg
  students/1714080902617/lab_4提交订单MVC.jpg
  students/1714080902617/lab_4选桌MVC.jpg
Labels: Good

#1710 #4 #5 #552 实验四五：类建模
  students/1714080902623/Lab45.md
  students/1714080902623/Lb4_出售类图.jpg
  students/1714080902623/Lb4_采购类图.jpg
Labels: Good

#1704 #4 #5 #397 实验四五：类建模
  students/1714080902212/ClassDiagram1.jpg
  students/1714080902212/ClassDiagram2.jpg
  students/1714080902212/ClassDiagram3.jpg
  students/1714080902212/lab4&5.md
Labels: Good

#1721 #4 #5 #376 实验四五 类建模 #3 #376 补交实验三 过程建模
  students/1714080901120/Lab3_ActivityDiagram1.jpg
  students/1714080901120/Lab3_ActivityDiagram2.jpg
  students/1714080901120/Lab4_ClassDiagram1.jpg
  students/1714080901120/Lab4_ClassDiagram2.jpg
  students/1714080901120/lab2.md
  students/1714080901120/lab3.md
  students/1714080901120/lab4.md
Labels: Good

#1731 #4 #518 实验四 实验五
  students/1714080901133/lab1.md
  students/1714080901133/lab2.md
  students/1714080901133/lab3.md
  students/1714080901133/lab4.md
  students/1714080901133/model2.jpg
  students/1714080901133/model3_1.jpg
  students/1714080901133/model3_2.jpg
  students/1714080901133/model3_3.jpg
  students/1714080901133/model4_1.jpg
  students/1714080901133/model4_2.jpg
  students/1714080901133/model4_3.jpg
Labels: Excellent

#1736 #4 #5 #572 #类建模
  students/1714080902428/lab4-1.jpg
  students/1714080902428/lab4-2.jpg
  students/1714080902428/lab4-3.jpg
  students/1714080902428/lab4.md
Labels: Good

#1737 #4 #425 实验四&五：类建模
  students/1714080902309/delete.jpg
  students/1714080902309/deleteanote.jpg
  students/1714080902309/deletenote.jpg
  students/1714080902309/lab3.md
  students/1714080902309/lab4and5.md
  students/1714080902309/logoff.jpg
  students/1714080902309/logoffaaccount.jpg
  students/1714080902309/logoffaccount.jpg
  students/1714080902309/post.jpg
  students/1714080902309/postnote.jpg
  students/1714080902309/sendnote.jpg
Labels: Good

#1732 #4 #5 #213 实验四五：类建模
  students/1714080902207/lab02.md
  students/1714080902207/lab04-05.md
  students/1714080902207/审批空课室申请的类图.jpg
  students/1714080902207/查询空课室的类图.jpg
  students/1714080902207/申请空课室的类图.jpg
Labels: Good

#1756 #3 #4 #5 #865 实验四五：类建模/实验三：活动图修改
  students/1714080902503/Lab1.md
  students/1714080902503/Lab2.md
  students/1714080902503/Lab3_ActivityDiagram1.png
  students/1714080902503/Lab3_ActivityDiagram2.png
  students/1714080902503/Lab3_ActivityDiagram3.png
  students/1714080902503/Lab4_ClassDiagram1.png
  students/1714080902503/Lab4_ClassDiagram2.png
  students/1714080902503/Lab4_ClassDiagram3.png
  students/1714080902503/Lab_4&5.md
Labels: Excellent

#1764 #4 #5 #439 提交实验四、五，修改实验三
  students/1714080901136/Lab3_ActivityDiagram2.png
  students/1714080901136/Lab4&5.md
  students/1714080901136/Lab4&5_ClassDiagram1.png
  students/1714080901136/Lab4&5_ClassDiagram2.png
Labels: Good

#1779 #4 #5 #812 实验四五：类建模(第二次提交)
  students/1714080902126/lab4.md
  students/1714080902126/lab4_1.jpg
  students/1714080902126/lab4_2.jpg
  students/1714080902126/lab4_3.jpg
Labels: Good

#1788 #4 #5 #578 实验四五 类建模
  students/1714080902315/ActivityDiagram2.jpg
  students/1714080902315/ClassDiagram1.jpg
  students/1714080902315/ClassDiagram2.jpg
  students/1714080902315/lab2.md
  students/1714080902315/lab45.md
Labels: Good

#1801 实验四五：类建模
  students/1714080902103/Lab4_BuyGames.png
  students/1714080902103/Lab4_LoadGames.png
  students/1714080902103/Lab4_ReviseGames.png
  students/1714080902103/lab4.md
Labels: Good

#1820 #4 #5 #259 实验四五类建模
  students/1714080902311/lab4-5_Class1.jpg
  students/1714080902311/lab4-5_Class2.jpg
  students/1714080902311/lab4.md
Labels: Good

#1797 #4 #5 #497 实验四五：类建模/高级类建模
  students/1714080902605/lab2.md
  students/1714080902605/lab3.md
  students/1714080902605/lab45.md
  students/1714080902605/model2.jpg
  students/1714080902605/提交房源.jpg
  students/1714080902605/提交房源信息.jpg
  students/1714080902605/提交房源类图.jpg
  students/1714080902605/提交订单.jpg
  students/1714080902605/提交订单类图.jpg
  students/1714080902605/获取房源.jpg
  students/1714080902605/获取房源信息.jpg
  students/1714080902605/获取房源类图.jpg
Labels: Excellent

#1834 #2 #3 #4 #5 #534 实验四、五 | 修改实验二、三
  students/1714080901106/Lab3_ModifyActivityDiagram.jpg
  students/1714080901106/Lab4&5_DeleteClassDiagram.jpg
  students/1714080901106/Lab4&5_ModifyClassDiagram.jpg
  students/1714080901106/Lab4&5_PostClassDiagram.jpg
  students/1714080901106/lab2.md
  students/1714080901106/lab4&5.md
Labels: Good

#1837 #4 #5 #438 实验四五报告
  students/1714080902337/Lab4.md
  students/1714080902337/model4-1.jpg
  students/1714080902337/model4-2.jpg
Labels: Good

#1873 #4 #5 #1241 实验四五：类建模
  students/1714080902631/Activity1.jpg
  students/1714080902631/Activity2.jpg
  students/1714080902631/ClassDiagram1.jpg
  students/1714080902631/ClassDiagram2.jpg
  students/1714080902631/lab2.md
  students/1714080902631/lab4.md
Labels: Good

#1879 #2 #3 #4 #5 #1129 实验四、五以及修改实验二、三
  students/1714080902203/lab2.md
  students/1714080902203/lab3.md
  students/1714080902203/lab3_model3.jpg
  students/1714080902203/lab3_model4.jpg
  students/1714080902203/lab4.md
  students/1714080902203/lab4_model1.jpg
  students/1714080902203/lab4_model2.jpg
  students/1714080902203/lab4_model3.jpg
Labels: Good

#1900 #4 #5 #930 实验四&五 类建模与高级类建模 + 修改实验三报告
  students/1714080902123/Lab4-1.jpg
  students/1714080902123/Lab4-2.jpg
  students/1714080902123/Lab4-3.jpg
  students/1714080902123/lab3.md
  students/1714080902123/lab4.md
Labels: Good

#1935 #6 #458 实验六：交互建模
  students/1714080902624/add.jpg
  students/1714080902624/del.jpg
  students/1714080902624/lab2.md
  students/1714080902624/lab6.md
  students/1714080902624/上架新菜顺序图.jpg
  students/1714080902624/下架菜品顺序图.jpg
Labels: Good

#1955 #6 #329 实验六：交互建模，修改用例规约、活动图和类图
  students/1714080902529/Receive_MVC_ClassDiagram.jpg
  students/1714080902529/Receive_SequenceDiagram.jpg
  students/1714080902529/Send_MVC_ClassDiagram.jpg
  students/1714080902529/Send_SequenceDiagram.jpg
  students/1714080902529/lab2.md
  students/1714080902529/lab6.md
  students/1714080902529/发放优惠券_ActivityDiagram.jpg
  students/1714080902529/领取优惠券_ActivityDiagram.jpg
Labels: Good

#1957 #6 #489实验六：交互建模
  students/1714080902617/lab6.md
  students/1714080902617/lab_6处理订单顺序图.jpg
  students/1714080902617/lab_6提交订单顺序图.jpg
  students/1714080902617/lab_6选桌顺序图.jpg
Labels: Good

#1959 #6 #537 实验6 交互建模
  students/1714080902637/lab3.md
  students/1714080902637/lab4.md
  students/1714080902637/lab45_1.jpg
  students/1714080902637/lab45_2.jpg
  students/1714080902637/lab45_3.jpg
  students/1714080902637/lab4_2.jpg
  students/1714080902637/lab4_3.jpg
  students/1714080902637/lab6.md
  students/1714080902637/lab6_1.jpg
  students/1714080902637/lab6_2.jpg
  students/1714080902637/lab6_3.jpg
Labels: Good
