Repository hzuapps/uml-modeling-2020, pull requests merged in 2020-04, with the labels that each got.

#2046 #6 #179 实验六：类建模 ； #2 #3 #4&5 实验2，3，4&5修改
  students/1714080902132/lab2.md
  students/1714080902132/lab4&5.md
  students/1714080902132/lab6.md
  students/1714080902132/ticket_booking_ActivityDiagram.jpg
  students/1714080902132/ticket_booking_ClassDiagram.jpg
  students/1714080902132/ticket_booking_ClassDiagram2.jpg
  students/1714080902132/ticket_booking_SequenceDiagram.jpg
  students/1714080902132/ticket_refund_ActivityDiagram.jpg
  students/1714080902132/ticket_refund_ClassDiagram.jpg
  students/1714080902132/ticket_refund_ClassDiagram2.jpg
  students/1714080902132/ticket_refund_SequenceDiagram.jpg
Labels: Good

#2076 #3 #45 #6 #595 实验六：交互建模（修改实验三、实验四五）
  students/1714080902225/lab6.md
  students/1714080902225/modify.jpg
  students/1714080902225/record.jpg
  students/1714080902225/删除消费情况交互建模.jpg
  students/1714080902225/删除花费情况.jpg
  students/1714080902225/记录消费情况交互建模.jpg
  students/1714080902225/记录花费情况.jpg
Labels: Good

#2241 #7 #557 实验七：状态建模
  students/1714080902410/lab07.md
  students/1714080902410/model71.jpg
  students/1714080902410/model72.jpg
Labels: Good

#2251 #7 #883 实验七
  students/1714080902630/lab7.md
  students/1714080902630/一卡通的状态图.jpg
Labels: Good

#2292 #7 #475 提交实验七、修改了之前的实验
  students/1714080902533/Lab3_查看新闻.jpg
  students/1714080902533/Lab4_评论新闻.jpg
  students/1714080902533/Lab6_查看新闻.jpg
  students/1714080902533/Lab6_评论新闻.jpg
  students/1714080902533/Lab7_评论状态.jpg
  students/1714080902533/lab2.md
  students/1714080902533/lab7.md
Labels: Good

#2289 实验七
  students/1714080902539/002leitu.jpg
  students/1714080902539/lab7.md
  students/1714080902539/zhuangtaitu.jpg
Labels: Good

#2315 #06 #426 提交实验07
  students/1509081602625/Lab07_StateDiagram1.jpg
  students/1509081602625/Lab07_StateDiagram2.jpg
  students/1509081602625/lab07.md
Labels: Good

#2263 #7 #466 实验七：状态建模
  students/1714080902604/MVC03.jpg
  students/1714080902604/SequenceDiagram1.jpg
  students/1714080902604/SequenceDiagram2.jpg
  students/1714080902604/SequenceDiagram3.jpg
  students/1714080902604/StatechartDiagram.jpg
  students/1714080902604/lab7.md
Labels: Good

#2323 #7 #554 实验七：状态建模
  students/1714080902329/lab7.md
  students/1714080902329/人员状态图.jpg
Labels: Pass7

#2327 #7 #552 实验七：状态建模
  students/1714080902623/Lab7.md
  students/1714080902623/Lab7_手机的状态图.jpg
Labels: Good

#2331 #3 #6 #7 #148 实验七 状态建模+修改实验三和实验六
  students/1714080902318/Lab3_ActivitiesDiagram_Delete.jpg
  students/1714080902318/Lab6_SequenceDiagram_Add.jpg
  students/1714080902318/Lab6_SequenceDiagram_Delete.jpg
  students/1714080902318/Lab6_SequenceDiagram_Edit.jpg
  students/1714080902318/Lab7_StatechartDiagram_Scenery.jpg
  students/1714080902318/lab7.md
Labels: Good

#2332 实验7 #7 #472 状态建模
  students/1714080901107/StatechartDiagram1.jpg
  students/1714080901107/lab3.md
  students/1714080901107/lab7.md
  students/1714080901107/ssActivityDiagram1.jpg
  students/1714080901107/查询具体赛事活动图.jpg
Labels: Good

#2333 #7 #417 实验七 状态建模及前面实验修改
  students/1714080901203/lab2.md
  students/1714080901203/lab3.md
  students/1714080901203/lab7.md
  students/1714080901203/删除食品.jpg
  students/1714080901203/删除食品活动图.jpg
  students/1714080901203/删除食品顺序图.jpg
  students/1714080901203/录入食品信息活动图.jpg
  students/1714080901203/食品状态图.jpg
Labels: Good

#2337 #7 #486 实验七：状态建模
  students/1714080902606/lab7.md
  students/1714080902606/歌曲的状态图.jpg
Labels: Good

#2341 #7 #403 实验七：用例建模&修改之前的实验
  students/1714080902201/lab2.md
  students/1714080902201/lab3_ActivityDiagram1.jpg
  students/1714080902201/lab3_ActivityDiagram2.jpg
  students/1714080902201/lab4.md
  students/1714080902201/lab4_ClassDiagram1.jpg
  students/1714080902201/lab4_ClassDiagram2.jpg
  students/1714080902201/lab6.md
  students/1714080902201/lab6_SequenceDiagram1.jpg
  students/1714080902201/lab6_SequenceDiagram2.jpg
  students/1714080902201/lab7.md
  students/1714080902201/lab7_StatechartDiagram1.jpg
Labels: Good

#2229 #7 #555 实验7：状态建模
  students/1714080902210/Lab7.jpg
  students/1714080902210/Lab7.md
Labels: bug

#2374 #7 #959 实验七 交互建模（实验六的修改）
  students/1714080902615/ActivityDiagram32.jpg
  students/1714080902615/ClassDiagram1.jpg
  students/1714080902615/ClassDiagram2.jpg
  students/1714080902615/ClassDiagram3.jpg
  students/1714080902615/StatechartDiagram1.jpg
  students/1714080902615/lab7.md
  students/1714080902615/录入课程.jpg
  students/1714080902615/退选.jpg
  students/1714080902615/选课.jpg
Labels: bug

#2350 #7 #734 实验七：状态建模
  students/1714080902619/Lab7.md
  students/1714080902619/bookstate.jpg
Labels: bug

#2402 #2 #3 #4 #5 #6 #7 #1087 实验4,5,6,7及修改实验2,3
  students/1714080902406/UseCaseDiagram1.jpg
  students/1714080902406/lab2.md
  students/1714080902406/lab3.md
  students/1714080902406/lab3_1.jpg
  students/1714080902406/lab3_2.jpg
  students/1714080902406/lab4.md
  students/1714080902406/lab4_1.jpg
  students/1714080902406/lab4_2.jpg
  students/1714080902406/lab6.md
  students/1714080902406/lab6_1.jpg
  students/1714080902406/lab6_2.jpg
  students/1714080902406/lab7.md
  students/1714080902406/lab7_1.jpg
Labels: Good

#2416 #7 #495 实验七：状态建模
  students/1714080902639/lab7.md
  students/1714080902639/路由器的状态图.jpg
Labels: Excellent

#2417 #7 #1204 实验七：状态建模
  students/1714080902608/lab6_1.jpg
  students/1714080902608/lab6_2.jpg
  students/1714080902608/lab7.md
  students/1714080902608/lab7_1.jpg
Labels: Good

#2445 #7 #686 修改状态图
  students/1714080902435/lab6.jpg
  students/1714080902435/lab6.md
Labels: bug
